name: Test Backend

on:
    push:
        branches:
            - main
    pull_request:
        types:
            - opened
            - synchronize

jobs:
    test-backend:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
            - name: Set up Python
              uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
              with:
                  python-version: "3.11"
            - name: Install dependencies
              run: pip install -r requirements/dev.txt
            - name: Run tests
              run: pytest tests/
            
            - name: Migrate DB
              run: bash scripts/prestart.sh
              working-directory: .
            - name: Run tests
              run: bash scripts/tests-start.sh "Coverage for ${{ github.sha }}"
              working-directory: .
            - run: docker compose down -v --remove-orphans
